### ISSUE TITLE
waterusedb updates

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/WaterUseServices#12]
In SS account
- [x] Change name of waterusetest. rds to just wateruse. (production version)
- [x] Create new postgres test rds named test. Which will host as a single test rds with multiple testing schemas

**Comment by aaronstephenson** [comment]
@jknewson still need this done?

**Comment by jknewson** [comment]
Yes, when you have time.

**Comment by aaronstephenson** [comment]
Test DB created.

**Comment by aaronstephenson** [comment]
waterusetest DB renamed to wateruse. Note it now has a new endpoint:
wateruse.c69uuui2tzs0.us-east-1.rds.amazonaws.com
